//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Transactions = new HashSet<Transaction>();
            this.Reminders = new HashSet<Reminder>();
        }
    
        public int ID { get; set; }
        public string BankName { get; set; }
        public Nullable<int> AcountNumber { get; set; }
        public string CardNumber { get; set; }
    
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<Reminder> Reminders { get; set; }
    }
}
