//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int ID { get; set; }
        public int AccountID { get; set; }
        public string Change { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public int Money { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
